#!/bin/bash

# Undo setup
#unset ANACONDA_ENV_NAME
#unset ANACONDA_BASEDIR_NAME

# Restore variables
export CUDA_HOME="$PRE_CUDA_HOME"
export LD_LIBRARY_PATH="$PRE_LD_LIBRARY_PATH"
export CPATH="$PRE_CPATH"
export HOROVOD_CUDA_HOME="$PRE_HOROVOD_CUDA_HOME"
export HOROVOD_CUDA_INCLUDE="$PRE_HOROVOD_CUDA_INCLUDE"
export HOROVOD_CUDA_LIB="$PRE_HOROVOD_CUDA_LIB"
export HOROVOD_GPU_ALLREDUCE="$PRE_HOROVOD_GPU_ALLREDUCE"
export HOROVOD_NCCL_HOME="$PRE_HOROVOD_NCCL_HOME"
export HOROVOD_NCCL_INCLUDE="$PRE_HOROVOD_NCCL_INCLUDE"
export HOROVOD_NCCL_LIB="$PRE_HOROVOD_NCCL_LIB"
export PYTHONUSERBASE="$PRE_PYTHONUSERBASE"

# Unset backup variables
unset PRE_CUDA_HOME
unset PRE_LD_LIBRARY_PATH
unset PRE_CPATH
unset PRE_HOROVOD_CUDA_HOME
unset PRE_HOROVOD_CUDA_INCLUDE
unset PRE_HOROVOD_CUDA_LIB
unset PRE_HOROVOD_GPU_ALLREDUCE
unset PRE_HOROVOD_NCCL_HOME
unset PRE_HOROVOD_NCCL_INCLUDE
unset PRE_HOROVOD_NCCL_LIB
unset PRE_PYTHONUSERBASE
